<?php
declare(strict_types=1);
function client_ip():string{foreach([$_SERVER['HTTP_CF_CONNECTING_IP']??'',$_SERVER['HTTP_X_FORWARDED_FOR']??'',$_SERVER['REMOTE_ADDR']??'']as$c){$ip=trim(explode(',',$c)[0]??'');if($ip!=='')return substr($ip,0,45);}return'0.0.0.0';}
function bearer_token():?string{$h=$_SERVER['HTTP_AUTHORIZATION']??$_SERVER['REDIRECT_HTTP_AUTHORIZATION']??'';if($h===''&&function_exists('apache_request_headers')){$hs=apache_request_headers();$h=$hs['Authorization']??$hs['authorization']??'';}return preg_match('/Bearer\s+(\S+)/i',$h,$m)?$m[1]:null;}
function token_hash(string $t):string{$secret=(string)app_config('app.token_hash_secret','');return$secret!==''?hash_hmac('sha256',$t,$secret):hash('sha256',$t);}function issue_token(PDO $pdo,int $uid):string{$raw=bin2hex(random_bytes(32));$exp=date('Y-m-d H:i:s',time()+((int)app_config('app.token_ttl_days',30)*86400));$pdo->prepare('INSERT INTO auth_tokens (user_id,token_hash,expires_at,user_agent,ip,created_at) VALUES (?,?,?,?,?,NOW())')->execute([$uid,token_hash($raw),$exp,substr($_SERVER['HTTP_USER_AGENT']??'',0,255),client_ip()]);return$raw;}
function current_auth():?array{static $c=false;if($c!==false)return$c;$t=bearer_token();if($t===null)return null;$pdo=Database::pdo();$st=$pdo->prepare('SELECT t.*,u.email,u.password_hash,u.name,u.role,u.status,u.created_at,u.updated_at,u.last_login_at FROM auth_tokens t JOIN users u ON u.id=t.user_id WHERE t.token_hash=? AND t.expires_at>NOW() LIMIT 1');$st->execute([token_hash($t)]);$r=$st->fetch();if(!$r||$r['status']!=='active')return null;$c=['token'=>['id'=>(int)$r['id'],'user_id'=>(int)$r['user_id'],'expires_at'=>$r['expires_at']],'user'=>['id'=>(int)$r['user_id'],'email'=>$r['email'],'password_hash'=>$r['password_hash'],'name'=>$r['name'],'role'=>$r['role'],'status'=>$r['status'],'created_at'=>$r['created_at'],'updated_at'=>$r['updated_at'],'last_login_at'=>$r['last_login_at']]];return$c;}
function require_auth():array{$a=current_auth();if($a===null)error_response('UNAUTHORIZED','برای دسترسی به این بخش باید وارد حساب کاربری شوید.',401);return$a;}
function revoke_current_token(PDO $pdo):void{$a=current_auth();if($a)$pdo->prepare('DELETE FROM auth_tokens WHERE id=?')->execute([(int)$a['token']['id']]);}
function is_within_rate_limit(PDO $pdo,string $key,int $max,int $win):bool{$now=time();$st=$pdo->prepare('SELECT * FROM rate_limits WHERE rate_key=? LIMIT 1');$st->execute([$key]);$r=$st->fetch();if(!$r||strtotime($r['window_start'])+$win<=$now){$pdo->prepare('REPLACE INTO rate_limits (rate_key,attempts,window_start,expires_at) VALUES (?,1,?,?)')->execute([$key,date('Y-m-d H:i:s',$now),date('Y-m-d H:i:s',$now+$win)]);return true;}if((int)$r['attempts']>=$max)return false;$pdo->prepare('UPDATE rate_limits SET attempts=attempts+1,expires_at=? WHERE rate_key=?')->execute([date('Y-m-d H:i:s',$now+$win),$key]);return true;}
function rate_limit_clear(PDO $pdo,string $key):void{$pdo->prepare('DELETE FROM rate_limits WHERE rate_key=?')->execute([$key]);}
function enforce_rate_limit(PDO $pdo,string $bucket,int $max,int $win):void{if(!is_within_rate_limit($pdo,$bucket.':'.client_ip(),$max,$win))error_response('RATE_LIMITED','تعداد درخواست‌ها زیاد است. لطفاً کمی بعد دوباره تلاش کنید.',429);}
