<?php
declare(strict_types=1);
function skill_keys():array{return['analysis','creativity','speed','quality','teamwork','decisionMaking','memory','math','perception','visualization','orientation','focus','multitasking'];}
function cognitive_raw_keys():array{return['A9a_Corsi','A9b_Paired','A9c_NBack','A10_Math','A10Plus_Pattern','A11_Speed','A12_Visual','A13_Orient','A14_Stroop','A15_Multi','A17_Decision','A18_Fact'];}
function default_skills():array{return array_fill_keys(skill_keys(),0);}function default_cognitive_raw():array{return array_fill_keys(cognitive_raw_keys(),0);}function default_t_scores():array{return['MI'=>0,'AI'=>0,'RI'=>0,'SI'=>0,'EI'=>0,'TCS'=>0];}function default_memory_sub_scores():array{return['corsi'=>0,'pairs'=>0,'nback'=>0];}
function get_tier_title(int $l):string{if($l===0)return'مبتدی';if($l<3)return'سطح C (مقدماتی)';if($l<5)return'سطح B (متوسط)';if($l<10)return'سطح A (پیشرفته)';return'سطح S (خبره)';}
function json_for_db($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}function decode_json_map($j,array $def,bool $only=true):array{$d=is_array($j)?$j:json_decode((string)$j,true);if(!is_array($d))$d=[];$out=$def;foreach($d as$k=>$v){if($only&&!array_key_exists($k,$def))continue;$out[$k]=is_numeric($v)?(int)round((float)$v):$v;}return$out;}function decode_json_list_field($j,array $def=[]):array{$d=is_array($j)?$j:json_decode((string)$j,true);return unique_string_list($d,$def);}
function initial_profile_state():array{return['level_number'=>0,'level_title'=>get_tier_title(0),'current_xp'=>0,'required_xp'=>500,'coins'=>0,'streak'=>0,'last_activity_date'=>null,'total_scenarios'=>0,'skills'=>default_skills(),'cognitive_raw'=>default_cognitive_raw(),'cognitive_t'=>default_t_scores(),'big_five'=>null,'memory_sub_scores'=>default_memory_sub_scores(),'badges'=>[],'unlocked_nodes'=>['node-1'],'completed_nodes'=>[]];}
function create_initial_profile(PDO $pdo,int $uid):void{$s=initial_profile_state();$q='INSERT INTO user_profiles (user_id,level_number,level_title,current_xp,required_xp,coins,streak,last_activity_date,total_scenarios,skills,cognitive_raw,cognitive_t,big_five,memory_sub_scores,badges,unlocked_nodes,completed_nodes,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())';$pdo->prepare($q)->execute([$uid,$s['level_number'],$s['level_title'],$s['current_xp'],$s['required_xp'],$s['coins'],$s['streak'],$s['last_activity_date'],$s['total_scenarios'],json_for_db($s['skills']),json_for_db($s['cognitive_raw']),json_for_db($s['cognitive_t']),null,json_for_db($s['memory_sub_scores']),json_for_db($s['badges']),json_for_db($s['unlocked_nodes']),json_for_db($s['completed_nodes'])]);}
function profile_row_to_state(array $r):array{$s=initial_profile_state();$s['level_number']=(int)($r['level_number']??0);$s['level_title']=(string)($r['level_title']??get_tier_title($s['level_number']));$s['current_xp']=(int)($r['current_xp']??0);$s['required_xp']=(int)($r['required_xp']??500);$s['coins']=(int)($r['coins']??0);$s['streak']=(int)($r['streak']??0);$s['last_activity_date']=$r['last_activity_date']??null;$s['total_scenarios']=(int)($r['total_scenarios']??0);$s['skills']=decode_json_map($r['skills']??'{}',default_skills(),true);$s['cognitive_raw']=decode_json_map($r['cognitive_raw']??'{}',default_cognitive_raw(),true);$s['cognitive_t']=decode_json_map($r['cognitive_t']??'{}',default_t_scores(),true);$s['big_five']=$r['big_five']===null?null:decode_json_map($r['big_five'],['Openness'=>50,'Conscientiousness'=>50,'Extraversion'=>50,'Agreeableness'=>50,'Neuroticism'=>50],true);$s['memory_sub_scores']=decode_json_map($r['memory_sub_scores']??'{}',default_memory_sub_scores(),true);$s['badges']=decode_json_list_field($r['badges']??'[]',[]);$s['unlocked_nodes']=decode_json_list_field($r['unlocked_nodes']??'["node-1"]',['node-1']);if(!$s['unlocked_nodes'])$s['unlocked_nodes']=['node-1'];$s['completed_nodes']=decode_json_list_field($r['completed_nodes']??'[]',[]);return$s;}
function load_profile_state(PDO $pdo,int $uid,bool $forUpdate=false):array{$st=$pdo->prepare('SELECT * FROM user_profiles WHERE user_id=?'.($forUpdate?' FOR UPDATE':''));$st->execute([$uid]);$r=$st->fetch();if(!$r){create_initial_profile($pdo,$uid);$st=$pdo->prepare('SELECT * FROM user_profiles WHERE user_id=?'.($forUpdate?' FOR UPDATE':''));$st->execute([$uid]);$r=$st->fetch();}return profile_row_to_state($r);}
function save_profile_state(PDO $pdo,int $uid,array $s):void{$s['level_title']=get_tier_title((int)$s['level_number']);$q='UPDATE user_profiles SET level_number=?,level_title=?,current_xp=?,required_xp=?,coins=?,streak=?,last_activity_date=?,total_scenarios=?,skills=?,cognitive_raw=?,cognitive_t=?,big_five=?,memory_sub_scores=?,badges=?,unlocked_nodes=?,completed_nodes=?,updated_at=NOW() WHERE user_id=?';$pdo->prepare($q)->execute([(int)$s['level_number'],$s['level_title'],(int)$s['current_xp'],(int)$s['required_xp'],(int)$s['coins'],(int)$s['streak'],$s['last_activity_date'],(int)$s['total_scenarios'],json_for_db($s['skills']),json_for_db($s['cognitive_raw']),json_for_db($s['cognitive_t']),$s['big_five']===null?null:json_for_db($s['big_five']),json_for_db($s['memory_sub_scores']),json_for_db($s['badges']),json_for_db($s['unlocked_nodes']),json_for_db($s['completed_nodes']),$uid]);}
function build_user_profile(array $u,array $s):array{$p=['name'=>(string)$u['name'],'role'=>(string)$u['role'],'level'=>get_tier_title((int)$s['level_number']),'levelNumber'=>(int)$s['level_number'],'currentXp'=>(int)$s['current_xp'],'requiredXp'=>(int)$s['required_xp'],'totalScenarios'=>(int)$s['total_scenarios'],'badges'=>$s['badges'],'skills'=>$s['skills'],'cognitiveProfile'=>['rawScores'=>$s['cognitive_raw'],'tScores'=>$s['cognitive_t']],'coins'=>(int)$s['coins'],'streak'=>(int)$s['streak'],'unlockedNodes'=>$s['unlocked_nodes'],'completedNodes'=>$s['completed_nodes'],'memorySubScores'=>$s['memory_sub_scores']];if($s['big_five']!==null)$p['bigFive']=$s['big_five'];return$p;}
function public_user(array $u):array{return['id'=>(int)$u['id'],'email'=>(string)$u['email'],'name'=>(string)$u['name'],'role'=>(string)$u['role'],'status'=>(string)$u['status'],'createdAt'=>$u['created_at']??null,'lastLoginAt'=>$u['last_login_at']??null];}function fetch_user_by_id(PDO $pdo,int $uid):?array{$st=$pdo->prepare('SELECT * FROM users WHERE id=? LIMIT 1');$st->execute([$uid]);$u=$st->fetch();return$u?:null;}
function apply_activity_streak(array &$s):void{$today=date('Y-m-d');$last=$s['last_activity_date'];if($last===$today)return;$s['streak']=$last?(($last===date('Y-m-d',strtotime($today.' -1 day')))?(int)$s['streak']+1:1):1;$s['last_activity_date']=$today;}
function apply_assessment_points(array &$s,int $points):array{$points=max(0,$points);$req=max(1,(int)$s['required_xp']);$old=(int)$s['level_number'];$xp=(int)$s['current_xp']+$points;$lvl=$old;if($xp>=$req){$xp-=$req;$lvl++;}$s['current_xp']=$xp;$s['level_number']=$lvl;$s['level_title']=get_tier_title($lvl);return['xpEarned'=>$points,'leveledUp'=>$lvl>$old,'oldLevel'=>$old,'newLevel'=>$lvl];}
function set_skill_max(array &$skills,string $key,float $score):void{if(!array_key_exists($key,$skills))return;$score=(int)round(max(0,min(100,$score)));$skills[$key]=max((int)$skills[$key],$score);}function apply_skill_update(array &$sk,string $g,float $raw):void{$s=max(0,min(100,$raw));if($g==='MINIGAME_MATH'){set_skill_max($sk,'math',$s);set_skill_max($sk,'analysis',round($s*.7));}elseif($g==='MINIGAME_PATTERN'){set_skill_max($sk,'analysis',$s);set_skill_max($sk,'math',round($s*.5));}elseif($g==='MINIGAME_SPEED'){set_skill_max($sk,'perception',$s);set_skill_max($sk,'speed',$s);}elseif($g==='MINIGAME_VISUALIZATION')set_skill_max($sk,'visualization',$s);elseif($g==='MINIGAME_ORIENTATION')set_skill_max($sk,'orientation',$s);elseif($g==='MINIGAME_STROOP')set_skill_max($sk,'focus',$s);elseif($g==='MINIGAME_MULTITASK')set_skill_max($sk,'multitasking',$s);elseif($g==='MINIGAME_FACTFINDING')set_skill_max($sk,'decisionMaking',$s);elseif($g==='MINIGAME_5WHYS')set_skill_max($sk,'analysis',$s);elseif($g==='MINIGAME_SWOT'){set_skill_max($sk,'analysis',$s);set_skill_max($sk,'decisionMaking',$s);}elseif($g==='MINIGAME_CYNEFIN')set_skill_max($sk,'decisionMaking',$s);}
function complete_journey_node(array &$s,?string $nodeId):array{if($nodeId===null||$nodeId===''||!in_array($nodeId,$s['unlocked_nodes'],true))return['completed'=>false,'unlockedNext'=>null,'coinReward'=>0];$new=false;if(!in_array($nodeId,$s['completed_nodes'],true)){$s['completed_nodes'][]=$nodeId;$new=true;}$next=next_journey_node_id($nodeId);if($next!==null&&!in_array($next,$s['unlocked_nodes'],true))$s['unlocked_nodes'][]=$next;$coin=0;if($new){$n=get_journey_node($nodeId);$coin=(int)($n['coinReward']??0);$s['coins']=(int)$s['coins']+$coin;}return['completed'=>$new,'unlockedNext'=>$next,'coinReward'=>$coin];}
function payload_number(array $p,array $keys,$def=null){foreach($keys as$k)if(array_key_exists($k,$p)&&is_numeric($p[$k]))return(float)$p[$k];return$def;}
// Best-attempt policy: cognitive raw scores only ever improve, matching how
// skills are stored via set_skill_max. Overwriting with the latest attempt let
// a worse retry lower an already-earned T-score while skills kept the best run.
function set_raw_max(array &$raw,string $key,float $score):void{$raw[$key]=max((float)($raw[$key]??0),$score);}
function apply_cognitive_raw_update(array &$raw,string $g,float $score,array $payload=[]):bool{if($g==='MINIGAME_MATH')set_raw_max($raw,'A10_Math',$score);elseif($g==='MINIGAME_PATTERN')set_raw_max($raw,'A10Plus_Pattern',$score);elseif($g==='MINIGAME_SPEED')set_raw_max($raw,'A11_Speed',$score);elseif($g==='MINIGAME_VISUALIZATION')set_raw_max($raw,'A12_Visual',$score);elseif($g==='MINIGAME_ORIENTATION')set_raw_max($raw,'A13_Orient',$score);elseif($g==='MINIGAME_STROOP')set_raw_max($raw,'A14_Stroop',$score);elseif($g==='MINIGAME_MULTITASK')set_raw_max($raw,'A15_Multi',$score);elseif($g==='MINIGAME_FACTFINDING')set_raw_max($raw,'A18_Fact',$score);elseif($g==='MINIGAME_MEMORY'){$src=$payload['rawScores']??($payload['cognitiveRaw']??$payload);if(!is_array($src))$src=[];$changed=false;$map=['A9a_Corsi'=>['A9a_Corsi','corsi','corsiRaw','span'],'A9b_Paired'=>['A9b_Paired','pairs','paired','pairedRaw','accuracy'],'A9c_NBack'=>['A9c_NBack','nback','nBack','dPrime']];foreach($map as$rk=>$aliases){$v=payload_number($src,$aliases,null);if($v!==null){set_raw_max($raw,$rk,(float)$v);$changed=true;}}if(!$changed)set_raw_max($raw,'A9c_NBack',$score);}else return false;return true;}
